# ============================================
# Конфигурация приложения
# ============================================

# Параметры подключения к БД
db.host=localhost
db.port=3050
db.path=D:\\anan.fdb
db.user=SYSDBA
db.password=masterkey

# Выбор варианта интерфейса (view):
# - swing
# - javafx
# - console
app.view=swing

# Выбор алгоритма подбора программы (calculator):
# - weight_loss (похудение)
# - muscle_gain (набор массы)
# - maintenance (поддержание)
app.calculator=muscle_gain

# Выбор способа хранения (storage):
# - database (база данных)
# - file (JSON файл)
# - image (PNG изображение)
app.storage=database