# ============================================
# ???????????? ??????????
# ============================================

# ????????? ???? ??????
db.host=localhost
db.port=3050
db.path=D:\\anan.fdb
db.user=SYSDBA
db.password=masterkey

# ????? ?????????? ?????????? (view):
# - swing
# - javafx
# - console
app.view=swing

# ????? ???????????? ?????????? (calculator):
# - weight_loss (?????????)
# - muscle_gain (????? ?????)
# - maintenance (???????????)
app.calculator=muscle_gain

# ????? ????????? ????????? (storage):
# - database (???? ??????)
# - file (JSON ????)
# - image (PNG ?????)
app.storage=database