DROP TABLE progress_logs;
DROP TABLE user_programs;
DROP TABLE program_exercises;
DROP TABLE workout_programs;
DROP TABLE exercises;
DROP TABLE admins;
DROP TABLE users;

CREATE TABLE users (
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(100) NOT NULL UNIQUE,
                       password VARCHAR(100) NOT NULL,
                       height DECIMAL(5,2) NOT NULL,
                       weight DECIMAL(5,2) NOT NULL,
                       age INTEGER NOT NULL,
                       gender VARCHAR(10) NOT NULL,
                       goal VARCHAR(20) NOT NULL,
                       location VARCHAR(20) NOT NULL,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admins (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        login VARCHAR(50) NOT NULL UNIQUE,
                        password VARCHAR(100) NOT NULL
);

INSERT INTO admins (login, password) VALUES ('admin', 'admin');

CREATE TABLE exercises (
                           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(100) NOT NULL,
                           description VARCHAR(500),
                           muscle_group VARCHAR(50),
                           equipment VARCHAR(50),
                           difficulty VARCHAR(20)
);

CREATE TABLE workout_programs (
                                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  name VARCHAR(100) NOT NULL,
                                  goal VARCHAR(20) NOT NULL,
                                  location VARCHAR(20) NOT NULL,
                                  description VARCHAR(500)
);

CREATE TABLE program_exercises (
                                   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   program_id INTEGER NOT NULL,
                                   exercise_id INTEGER NOT NULL,
                                   sets INTEGER NOT NULL,
                                   reps VARCHAR(20) NOT NULL,
                                   exercise_order INTEGER NOT NULL,
                                   FOREIGN KEY (program_id) REFERENCES workout_programs(id) ON DELETE CASCADE,
                                   FOREIGN KEY (exercise_id) REFERENCES exercises(id)
);

CREATE TABLE user_programs (
                               id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id INTEGER NOT NULL,
                               program_id INTEGER NOT NULL,
                               assigned_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                               FOREIGN KEY (program_id) REFERENCES workout_programs(id)
);

CREATE TABLE progress_logs (
                               id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id INTEGER NOT NULL,
                               log_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               weight DECIMAL(5,2),
                               exercise_completed BOOLEAN DEFAULT FALSE,
                               notes VARCHAR(500),
                               FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ГЕНЕРАТОРЫ И ТРИГГЕРЫ
CREATE GENERATOR gen_users;
CREATE GENERATOR gen_admins;
CREATE GENERATOR gen_exercises;
CREATE GENERATOR gen_workout_programs;
CREATE GENERATOR gen_program_exercises;
CREATE GENERATOR gen_user_programs;
CREATE GENERATOR gen_progress_logs;

SET TERM ^ ;

CREATE TRIGGER trg_users_id FOR users ACTIVE BEFORE INSERT POSITION 0 AS BEGIN IF (NEW.id IS NULL) THEN NEW.id = GEN_ID(gen_users, 1); END^
CREATE TRIGGER trg_admins_id FOR admins ACTIVE BEFORE INSERT POSITION 0 AS BEGIN IF (NEW.id IS NULL) THEN NEW.id = GEN_ID(gen_admins, 1); END^
CREATE TRIGGER trg_exercises_id FOR exercises ACTIVE BEFORE INSERT POSITION 0 AS BEGIN IF (NEW.id IS NULL) THEN NEW.id = GEN_ID(gen_exercises, 1); END^
CREATE TRIGGER trg_workout_programs_id FOR workout_programs ACTIVE BEFORE INSERT POSITION 0 AS BEGIN IF (NEW.id IS NULL) THEN NEW.id = GEN_ID(gen_workout_programs, 1); END^
CREATE TRIGGER trg_program_exercises_id FOR program_exercises ACTIVE BEFORE INSERT POSITION 0 AS BEGIN IF (NEW.id IS NULL) THEN NEW.id = GEN_ID(gen_program_exercises, 1); END^
CREATE TRIGGER trg_user_programs_id FOR user_programs ACTIVE BEFORE INSERT POSITION 0 AS BEGIN IF (NEW.id IS NULL) THEN NEW.id = GEN_ID(gen_user_programs, 1); END^
CREATE TRIGGER trg_progress_logs_id FOR progress_logs ACTIVE BEFORE INSERT POSITION 0 AS BEGIN IF (NEW.id IS NULL) THEN NEW.id = GEN_ID(gen_progress_logs, 1); END^

SET TERM ; ^

-- УПРАЖНЕНИЯ
INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES ('Жим штанги лёжа', 'Базовое упражнение для развития грудных мышц', 'Грудь', 'Штанга', 'Средний');
INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES ('Приседания со штангой', 'Базовое упражнение для развития мышц ног', 'Ноги', 'Штанга', 'Средний');
INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES ('Становая тяга', 'Базовое упражнение для спины и ног', 'Спина', 'Штанга', 'Сложный');
INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES ('Жим штанги стоя', 'Упражнение для развития плечевого пояса', 'Плечи', 'Штанга', 'Средний');
INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES ('Подтягивания', 'Упражнение для развития мышц спины', 'Спина', 'Собственный вес', 'Средний');
INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES ('Отжимания от пола', 'Упражнение для грудных мышц и трицепса', 'Грудь', 'Собственный вес', 'Лёгкий');
INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES ('Выпады с гантелями', 'Упражнение для развития мышц ног', 'Ноги', 'Гантели', 'Лёгкий');
INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES ('Тяга гантели в наклоне', 'Упражнение для развития мышц спины', 'Спина', 'Гантели', 'Лёгкий');
INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES ('Жим гантелей лёжа', 'Упражнение для грудных мышц с гантелями', 'Грудь', 'Гантели', 'Средний');
INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES ('Подъём штанги на бицепс', 'Упражнение для развития бицепса', 'Руки', 'Штанга', 'Лёгкий');
INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES ('Французский жим', 'Упражнение для развития трицепса', 'Руки', 'Штанга', 'Средний');
INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES ('Разведение гантелей в стороны', 'Упражнение для развития средних пучков дельт', 'Плечи', 'Гантели', 'Лёгкий');
INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES ('Планка', 'Статическое упражнение для мышц кора', 'Пресс', 'Собственный вес', 'Лёгкий');
INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES ('Скручивания', 'Упражнение для развития прямой мышцы живота', 'Пресс', 'Собственный вес', 'Лёгкий');
INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES ('Бёрпи', 'Комплексное кардио упражнение', 'Всё тело', 'Собственный вес', 'Средний');

-- ПРОГРАММЫ
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (1, 'День 1: Грудь + Трицепс', 'mass_gain', 'gym', 'Тренировка грудных мышц и трицепса в зале');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (2, 'День 2: Спина + Бицепс', 'mass_gain', 'gym', 'Тренировка спины и бицепса в зале');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (3, 'День 3: Ноги + Плечи', 'mass_gain', 'gym', 'Тренировка ног и плеч в зале');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (4, 'День 1: Грудь + Трицепс', 'mass_gain', 'home', 'Домашняя тренировка груди и трицепса');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (5, 'День 2: Спина + Бицепс', 'mass_gain', 'home', 'Домашняя тренировка спины и бицепса');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (6, 'День 3: Ноги + Плечи', 'mass_gain', 'home', 'Домашняя тренировка ног и плеч');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (7, 'День 1: Кардио + Пресс', 'weight_loss', 'gym', 'Кардио тренировка для сжигания жира');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (8, 'День 2: Фуллбоди', 'weight_loss', 'gym', 'Круговая тренировка на всё тело');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (9, 'День 3: Интервальная HIIT', 'weight_loss', 'gym', 'Высокоинтенсивная интервальная тренировка');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (10, 'День 1: Кардио + Пресс (Дом)', 'weight_loss', 'home', 'Домашняя кардио тренировка');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (11, 'День 2: Фуллбоди (Дом)', 'weight_loss', 'home', 'Домашняя круговая тренировка');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (12, 'День 3: HIIT (Дом)', 'weight_loss', 'home', 'Интервальная тренировка дома');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (13, 'День 1: Верх тела (Зал)', 'maintenance', 'gym', 'Поддержание формы верхней части тела');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (14, 'День 2: Низ тела (Зал)', 'maintenance', 'gym', 'Поддержание формы нижней части тела');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (15, 'День 3: Фуллбоди (Зал)', 'maintenance', 'gym', 'Общая тренировка на всё тело');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (16, 'День 1: Верх тела (Дом)', 'maintenance', 'home', 'Домашняя тренировка верха');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (17, 'День 2: Низ тела (Дом)', 'maintenance', 'home', 'Домашняя тренировка низа');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (18, 'День 3: Фуллбоди (Дом)', 'maintenance', 'home', 'Домашняя общая тренировка');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (19, 'День 1: Грудь + Трицепс (Микс)', 'mass_gain', 'mixed', 'Смешанная тренировка груди');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (20, 'День 2: Спина + Бицепс (Микс)', 'mass_gain', 'mixed', 'Смешанная тренировка спины');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (21, 'День 3: Ноги + Плечи (Микс)', 'mass_gain', 'mixed', 'Смешанная тренировка ног');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (22, 'День 1: Кардио + Пресс (Микс)', 'weight_loss', 'mixed', 'Смешанная кардио тренировка');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (23, 'День 2: Фуллбоди (Микс)', 'weight_loss', 'mixed', 'Смешанная круговая тренировка');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (24, 'День 3: HIIT (Микс)', 'weight_loss', 'mixed', 'Смешанная интервальная тренировка');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (25, 'День 1: Верх тела (Микс)', 'maintenance', 'mixed', 'Смешанная тренировка верха');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (26, 'День 2: Низ тела (Микс)', 'maintenance', 'mixed', 'Смешанная тренировка низа');
INSERT INTO workout_programs (id, name, goal, location, description) VALUES (27, 'День 3: Фуллбоди (Микс)', 'maintenance', 'mixed', 'Смешанная общая тренировка');


-- День 1: Грудь + Трицепс (mass_gain, gym) - ID 1
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (1, 1, 4, '8-10', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (1, 9, 3, '10-12', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (1, 11, 3, '10-12', 3);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (1, 6, 3, '12-15', 4);

-- День 2: Спина + Бицепс (mass_gain, gym) - ID 2
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (2, 5, 4, '8-10', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (2, 3, 3, '8-10', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (2, 8, 3, '10-12', 3);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (2, 10, 3, '10-12', 4);

-- День 3: Ноги + Плечи (mass_gain, gym) - ID 3
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (3, 2, 4, '8-10', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (3, 7, 3, '12-15', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (3, 4, 3, '10-12', 3);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (3, 12, 3, '12-15', 4);

-- День 1: Грудь + Трицепс (mass_gain, home) - ID 4
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (4, 6, 4, '15-20', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (4, 11, 3, '12-15', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (4, 13, 3, '60 сек', 3);

-- День 2: Спина + Бицепс (mass_gain, home) - ID 5
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (5, 5, 4, '10-12', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (5, 8, 3, '12-15', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (5, 10, 3, '12-15', 3);

-- День 3: Ноги + Плечи (mass_gain, home) - ID 6
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (6, 7, 4, '15-20', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (6, 2, 3, '15-20', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (6, 12, 3, '15-20', 3);

-- День 1: Кардио + Пресс (weight_loss, gym) - ID 7
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (7, 15, 4, '15-20', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (7, 13, 3, '60 сек', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (7, 14, 3, '20-25', 3);

-- День 2: Фуллбоди (weight_loss, gym) - ID 8
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (8, 1, 3, '12-15', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (8, 2, 3, '12-15', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (8, 5, 3, '10-12', 3);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (8, 15, 3, '15-20', 4);

-- День 3: Интервальная (weight_loss, gym) - ID 9
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (9, 15, 4, '20-30', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (9, 6, 3, '15-20', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (9, 13, 3, '45 сек', 3);

-- День 1: Кардио + Пресс (weight_loss, home) - ID 10
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (10, 15, 4, '15-20', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (10, 6, 3, '15-20', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (10, 14, 3, '20-25', 3);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (10, 13, 3, '60 сек', 4);

-- День 2: Фуллбоди (weight_loss, home) - ID 11
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (11, 6, 3, '15-20', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (11, 7, 3, '15-20', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (11, 5, 3, '10-12', 3);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (11, 13, 3, '45 сек', 4);

-- День 3: HIIT (weight_loss, home) - ID 12
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (12, 15, 4, '20-30', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (12, 14, 3, '25-30', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (12, 13, 3, '60 сек', 3);

-- День 1: Верх тела (maintenance, gym) - ID 13
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (13, 1, 3, '10-12', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (13, 5, 3, '10-12', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (13, 4, 3, '12-15', 3);

-- День 2: Низ тела (maintenance, gym) - ID 14
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (14, 2, 3, '10-12', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (14, 7, 3, '12-15', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (14, 13, 3, '60 сек', 3);

-- День 3: Фуллбоди (maintenance, gym) - ID 15
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (15, 1, 3, '10-12', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (15, 2, 3, '10-12', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (15, 5, 3, '10-12', 3);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (15, 12, 3, '12-15', 4);

-- День 1: Верх тела (maintenance, home) - ID 16
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (16, 6, 3, '15-20', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (16, 5, 3, '10-12', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (16, 12, 3, '15-20', 3);

-- День 2: Низ тела (maintenance, home) - ID 17
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (17, 7, 3, '15-20', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (17, 2, 3, '15-20', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (17, 14, 3, '20-25', 3);

-- День 3: Фуллбоди (maintenance, home) - ID 18
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (18, 6, 3, '15-20', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (18, 7, 3, '15-20', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (18, 5, 3, '10-12', 3);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (18, 13, 3, '60 сек', 4);

-- День 1: Грудь + Трицепс (mass_gain, mixed) - ID 19
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (19, 1, 4, '8-10', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (19, 9, 3, '10-12', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (19, 11, 3, '10-12', 3);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (19, 6, 3, '12-15', 4);

-- День 2: Спина + Бицепс (mass_gain, mixed) - ID 20
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (20, 5, 4, '8-10', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (20, 3, 3, '8-10', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (20, 8, 3, '10-12', 3);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (20, 10, 3, '10-12', 4);

-- День 3: Ноги + Плечи (mass_gain, mixed) - ID 21
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (21, 2, 4, '8-10', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (21, 7, 3, '12-15', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (21, 4, 3, '10-12', 3);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (21, 12, 3, '12-15', 4);

-- День 1: Кардио + Пресс (weight_loss, mixed) - ID 22
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (22, 15, 4, '15-20', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (22, 13, 3, '60 сек', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (22, 14, 3, '20-25', 3);

-- День 2: Фуллбоди (weight_loss, mixed) - ID 23
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (23, 1, 3, '12-15', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (23, 2, 3, '12-15', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (23, 5, 3, '10-12', 3);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (23, 15, 3, '15-20', 4);

-- День 3: HIIT (weight_loss, mixed) - ID 24
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (24, 15, 4, '20-30', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (24, 6, 3, '15-20', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (24, 13, 3, '45 сек', 3);

-- День 1: Верх тела (maintenance, mixed) - ID 25
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (25, 1, 3, '10-12', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (25, 5, 3, '10-12', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (25, 4, 3, '12-15', 3);

-- День 2: Низ тела (maintenance, mixed) - ID 26
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (26, 2, 3, '10-12', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (26, 7, 3, '12-15', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (26, 13, 3, '60 сек', 3);

-- День 3: Фуллбоди (maintenance, mixed) - ID 27
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (27, 1, 3, '10-12', 1);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (27, 2, 3, '10-12', 2);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (27, 5, 3, '10-12', 3);
INSERT INTO program_exercises (program_id, exercise_id, sets, reps, exercise_order) VALUES (27, 12, 3, '12-15', 4);

COMMIT;